// Barrel: import from '@/lib/api' regardless of which resource module a call lives in.
export { listContexts } from './contexts'
export {
  listSessions,
  readSession,
  renameSession,
  deleteSession,
  type SessionMeta,
  type ChatMode,
  type ChatBubble,
} from './sessions'
export {
  getDev,
  getDevLog,
  getProposals,
  approveProposal,
  getProposalExecution,
  updateStagedArtifact,
  publishProposal,
  rejectProposal,
  dropProposal,
  getMemoryStats,
  getLearningRollup,
  type LearningRollup,
  runDistill,
  getFoundation,
  saveFoundationFile,
  getDeputyMandate,
  saveDeputyMandate,
  getHarnessPlugins,
  getLocalPlugins,
  getHarnessFile,
  saveHarnessFile,
  getPalette,
  getPublished,
  togglePublished,
  deletePublished,
  getPublishedFile,
  getConstitutions,
  toggleConstitution,
  getConstitutionFile,
  saveConstitutionFile,
  getAssets,
  assetAction,
  savePublishedFile,
  type PublishedFile,
  getGeneralDocs,
  getGeneralDoc,
  saveGeneralDoc,
  getProjectStatus,
  getRoadmap,
  getPortrait,
  type Portrait,
  getKnowledgeLint,
  type LintFinding,
  type LintReport,
  setWorkItemScaffold,
  type GeneralDocMeta,
  type ProjectStatus,
  type RoadmapBoard,
  type BoardDeliverable,
  type BoardWave,
  type BoardItem,
  addInbox,
  updateInbox,
  deleteInbox,
  pushInbox,
  planWorkItem,
  vetWorkItem,
  continueWorkItem,
  authorizeWorkItem,
  deleteWorkItem,
  getWorkItemDetail,
  getWorkItemArtifacts,
  advanceWorkItem,
  completeWorkItem,
  artifactPath,
  type Artifact,
  type WorkItemDetail,
  type RunArtifact,
  type TaskItem,
  type AdvanceResult,
  type CompleteResult,
  type PlanResult,
  type DeleteResult,
  type DevData,
  type DevEvent,
  type DevLogData,
  type MemoryProposal,
  type ProposalCandidate,
  type ProposalStep,
  type EvalReport,
  type MemoryStats,
  type CandidateItem,
  type KnowledgeItem,
  type DistillResult,
  type HarnessEntry,
  type HarnessScope,
  type HarnessFile,
  type FoundationFile,
  type FoundationConstitution,
  type PublishedItem,
  type ManagedConstitution,
  type AssetItem,
  type AssetAction,
  type PublishedForm,
  type ProposalsData,
  type ProposalScope,
  type ProposalStatus,
  type WorkItem,
  type WorkPhase,
  type WorkStatus,
  type InboxEntry,
  type InboxKind,
  type InboxStatus,
  type InboxOrigin,
  type PushResult,
  type DevGlance,
  // workspace-workflow S6/S7: gates, git surface, attention engine, graph, drilldown feeds
  getWorkItemGateBrief,
  abandonWorkItem,
  getWorkItemGit,
  syncWorkItemGit,
  mergeWorkItemGit,
  revertWorkItemGit,
  resolveWorkItemGit,
  getWorkItemPr,
  getWorkItemPrDiff,
  getWorkGraph,
  getAttention,
  markWorkItemSeen,
  compactWorkItem,
  type GateBrief,
  type AbandonResult,
  type GitHealth,
  type GitSyncResult,
  type GitMergeResult,
  type PrView,
  type PrDiff,
  type WorkGraphData,
  type WorkGraphNode,
  type WorkGraphEdge,
  type AttentionData,
  type AttentionRow,
  type AttentionBadge,
  type CheckpointStub,
} from './dev'
export { agentSocketUrl } from './agent'
export {
  getSystem,
  getRepos,
  getSystemAttention,
  type SystemHold,
  type SystemHoldKind,
  type SystemRepoAttention,
  getRuns,
  getRunTrace,
  type RunEvent,
  type RunTrace,
  getTokens,
  getTokenTimeseries,
  getInventory,
  type Inventory,
  type InvDatabase,
  type InvTable,
  type InvTool,
  setSystemModel,
  setRepoModel,
  setRepoLearning,
  setSystemLearning,
  setSystemDeputy,
  setSweepConfig,
  getCompactionConfig,
  setCompactionConfig,
  setSystemEffort,
  setRepoEffort,
  getAgentModels,
  setAgentModel,
  setAgentEffort,
  type AgentModels,
  type AgentModelRow,
  type SweepConfig,
  type CompactionConfig,
  setRepoMeta,
  type RepoMeta,
  setRepoGit,
  type RepoGit,
  browseFs,
  connectRepo,
  disconnectRepo,
  type DisconnectReceipt,
  type FsBrowse,
  type ConnectedRepo,
  type Scope,
  type Run,
  type SystemOverview,
  type ScopeStatus,
  type RepoOverview,
  type RunsData,
  type ModelAlias,
  type TokenUsage,
  type RepoTokens,
  type TokenBucket,
  type TokenTypeSplit,
  type CategoryNode,
  type TokenTimeseries,
  type TokenDay,
} from './system'
